print('===== EXERCÍCIO 009 =====')
print()

valor = int(input('Digite um Número: '))
print()

print('====== TABUADA DE ADIÇÃO ======')
print('{} +  1 = {}'.format(valor, valor + 1))
print('{} +  2 = {}'.format(valor, valor + 2))
print('{} +  3 = {}'.format(valor, valor + 3))
print('{} +  4 = {}'.format(valor, valor + 4))
print('{} +  5 = {}'.format(valor, valor + 5))
print('{} +  6 = {}'.format(valor, valor + 6))
print('{} +  7 = {}'.format(valor, valor + 7))
print('{} +  8 = {}'.format(valor, valor + 8))
print('{} +  9 = {}'.format(valor, valor + 9))
print('{} + 10 = {}'.format(valor, valor + 10))
print()

print('====== TABUADA DE SUBTRAÇÃO ======')
print('{} -  1 = {}'.format(valor, valor - 1))
print('{} -  2 = {}'.format(valor, valor - 2))
print('{} -  3 = {}'.format(valor, valor - 3))
print('{} -  4 = {}'.format(valor, valor - 4))
print('{} -  5 = {}'.format(valor, valor - 5))
print('{} -  6 = {}'.format(valor, valor - 6))
print('{} -  7 = {}'.format(valor, valor - 7))
print('{} -  8 = {}'.format(valor, valor - 8))
print('{} -  9 = {}'.format(valor, valor - 9))
print('{} - 10 = {}'.format(valor, valor - 10))
print()

print('====== TABUADA DE MULTIPLICAÇÃO ======')
print('{} x  1 = {}'.format(valor, valor * 1))
print('{} x  2 = {}'.format(valor, valor * 2))
print('{} x  3 = {}'.format(valor, valor * 3))
print('{} x  4 = {}'.format(valor, valor * 4))
print('{} x  5 = {}'.format(valor, valor * 5))
print('{} x  6 = {}'.format(valor, valor * 6))
print('{} x  7 = {}'.format(valor, valor * 7))
print('{} x  8 = {}'.format(valor, valor * 8))
print('{} x  9 = {}'.format(valor, valor * 9))
print('{} x 10 = {}'.format(valor, valor * 10))
print()

print('====== TABUADA DE DIVISÃO ======')	
print('{} /  1 = {:.2f}'.format(valor, valor / 1))
print('{} /  2 = {:.2f}'.format(valor, valor / 2))
print('{} /  3 = {:.2f}'.format(valor, valor / 3))
print('{} /  4 = {:.2f}'.format(valor, valor / 4))
print('{} /  5 = {:.2f}'.format(valor, valor / 5))
print('{} /  6 = {:.2f}'.format(valor, valor / 6))
print('{} /  7 = {:.2f}'.format(valor, valor / 7))
print('{} /  8 = {:.2f}'.format(valor, valor / 8))
print('{} /  9 = {:.2f}'.format(valor, valor / 9))
print('{} / 10 = {:.2f}'.format(valor, valor / 10))
print()
